Public Class clsMetadata

    ' This class provides methods to process metadata.
    ' In short, from metadata we get:
    '   1) edit form and confirm form
    '   2) relevant functions in regFuncs
    '   3) sql file
    '   4) xml file

    Public metadataArray() As String    ' Contains all metadata information.
    Public formArray() As String        ' Used to create HTML form
    Public sessionArray() As String     ' Used to create include functions
    Public dbArray() As String          ' Used to create database table sql file
    Public dbFieldLenArray() As String  ' Used to create HTML form and database table sql file

    Private vbindent As String = "    " ' Indent used by asp files.
    Private XMLIndent As String = "    "    ' Indent used by xml file.
    Private sqlIndent As String = "    "    ' indent used by sql file.

    Public targetDBTable As String  ' Used by sql file.

    Public DB_FUNCS_FILE As String ' Used by asp files - regFuncs.asp
    Public regAdminConfirmFileName As String ' Used by asp files - regFuncs.asp

    Private tableBorder As String
    Private tableWidth As String
    Private tablebgcolor As String
    Private tableFirstColWidth As String
    Private tableCellpadding As String
    Private tableCellspacing As String

    Public Function init(ByRef metadata As String, ByVal DBTableName As String, _
        ByVal DB_Funcs_File As String, ByVal regAdmConfirmFile As String, _
        Optional ByVal tableBorder As String = "", Optional ByVal tableWidth As String = "", _
        Optional ByVal tableBgColor As String = "", Optional ByVal tableFirstColWidth As String = "", _
        Optional ByVal cellpadding As String = "", Optional ByVal cellspacing As String = "") As Boolean
        Dim i, count As Integer

        ' Optional values
        Me.tableBorder = tableBorder
        Me.tableWidth = tableWidth
        Me.tablebgcolor = tableBgColor
        Me.tableFirstColWidth = tableFirstColWidth
        Me.tableCellpadding = cellpadding
        Me.tableCellspacing = cellspacing

        Me.metadataArray = Split(Trim(metadata), "|")
        count = UBound(metadataArray) - 1
        For i = 0 To count
            'metadataArray(i) = Trim(metadataArray(i))
            metadataArray(i) = MyUtil.chop(metadataArray(i))
            ' Encode the string so no asp code input is allowed to execute.
            'metadataArray(i) = Replace(metadataArray(i), "%", "&#37;")
            'tmp += "_start_" & metadataArray(i) & "_end_" & vbCrLf
        Next
        'MsgBox(tmp)

        If validateMetadata(metadataArray) = False Then Return False

        'Me.metadataArray = metadata
        Me.targetDBTable = DBTableName
        Me.DB_FUNCS_FILE = DB_Funcs_File
        Me.regAdminConfirmFileName = regAdmConfirmFile

        Me.parseMetadata()
        Return True
    End Function


    ' A simple validation. Future may have better validation.
    ' Now this basically works because all the other functions 
    ' use the ar array generated by paramDef() function.
    Function validateMetadata(ByRef metadataArray As String()) As Boolean
        If UBound(metadataArray) = 0 Then
            MsgBox("validateMetadata: Metadata cannot be empty.")
            Return False
        End If
        Return True
    End Function


    Public Function parseMetadata()
        Dim formArrayStr As String = ""
        Dim sessionArrayStr As String = ""
        Dim dbArrayStr As String = ""
        Dim dbFieldLenArrayStr As String = ""
        Dim passwordTmp As String = ""

        Dim i As Integer

        Dim count As Integer = UBound(metadataArray) - 1
        'MsgBox("ubound(metadataArray) = " & UBound(metadataArray) & ", " & metadataArray(count - 1) & ", " & metadataArray(count))

        For i = 0 To count
            If LCase(metadataArray(i + 1)) = "text" Or LCase(metadataArray(i + 1)) = "hidden" Then
                formArrayStr = formArrayStr & metadataArray(i + 2) & "|"
                sessionArrayStr = sessionArrayStr & metadataArray(i + 5) & "|"
                dbFieldLenArrayStr = dbFieldLenArrayStr & metadataArray(i + 4) & "|"
                i = i + 5
            ElseIf LCase(metadataArray(i + 1)) = "password" Then
                If passwordTmp = "" Then
                    formArrayStr = formArrayStr & metadataArray(i + 2) & "|"
                    sessionArrayStr = sessionArrayStr & metadataArray(i + 5) & "|"
                    passwordTmp = metadataArray(i + 2)
                    dbFieldLenArrayStr = dbFieldLenArrayStr & metadataArray(i + 4) & "|"
                End If
                i = i + 5
            ElseIf LCase(metadataArray(i + 1)) = "select" Then
                formArrayStr = formArrayStr & metadataArray(i + 2) & "|"
                sessionArrayStr = sessionArrayStr & metadataArray(i + 6) & "|"
                dbFieldLenArrayStr = dbFieldLenArrayStr & "4" & "|"
                count = CInt(metadataArray(i + 5))
                i = i + 5 + count
            ElseIf LCase(metadataArray(i + 1)) = "textarea" Then
                formArrayStr = formArrayStr & metadataArray(i + 2) & "|"
                sessionArrayStr = sessionArrayStr & metadataArray(i + 6) & "|"
                dbFieldLenArrayStr = dbFieldLenArrayStr & "TEXT" & "|"
                i = i + 6
            ElseIf LCase(metadataArray(i + 1)) = "radio" Then
                formArrayStr = formArrayStr & metadataArray(i + 2) & "|"
                sessionArrayStr = sessionArrayStr & metadataArray(i + 4) & "|"
                dbFieldLenArrayStr = dbFieldLenArrayStr & "4" & "|"
                count = CInt(metadataArray(i + 3))
                i = i + 3 + count
            ElseIf LCase(metadataArray(i + 1)) = "checkbox" Then
                formArrayStr = formArrayStr & metadataArray(i + 2) & "|"
                sessionArrayStr = sessionArrayStr & metadataArray(i + 4) & "|"
                dbFieldLenArrayStr = dbFieldLenArrayStr & "1" & "|"
                i = i + 4
            ElseIf LCase(metadataArray(i + 1)) = "comment" Then
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "blankline" Then
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "hr" Then
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "newtable" Then
                i = i + 1
            End If
        Next

        If Right(formArrayStr, 1) = "|" Then
            formArrayStr = Left(formArrayStr, Len(formArrayStr) - 1)
        End If

        If Right(sessionArrayStr, 1) = "|" Then
            sessionArrayStr = Left(sessionArrayStr, Len(sessionArrayStr) - 1)
        End If

        If Right(dbFieldLenArrayStr, 1) = "|" Then
            dbFieldLenArrayStr = Left(dbFieldLenArrayStr, Len(dbFieldLenArrayStr) - 1)
        End If

        Me.formArray = Split(formArrayStr, "|")
        Me.sessionArray = Split(sessionArrayStr, "|")
        Me.dbArray = sessionArray
        Me.dbFieldLenArray = Split(dbFieldLenArrayStr, "|")

        'MsgBox("formArray:" & vbCrLf & MyUtil.arrayToString(formArray, ",") & vbCrLf & _
        '        "sessionArray: " & vbCrLf & MyUtil.arrayToString(sessionArray, ",") & vbCrLf & _
        '       "dbArray: " & vbCrLf & MyUtil.arrayToString(dbArray, ",") & vbCrLf & _
        '      "dbFieldLenArray:" & vbCrLf & MyUtil.arrayToString(dbFieldLenArray, ","))

    End Function


    '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    ' XML system functions
    '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

    Public Function XMLEncode(ByVal var As String)
        XMLEncode = Replace(var, "&", "&amp;")
        XMLEncode = Replace(XMLEncode, ">", "&gt;")
        XMLEncode = Replace(XMLEncode, "<", "&lt;")
    End Function


    Public Function generateXML()
        Dim i, j, count As Integer
        Dim fieldsCounter As Integer = 0
        Dim XMLArray As String() '= Me.metadataArray
        ' Don't want to destroy the original metadataArray.
        'Array.Copy(Me.metadataArray, XMLArray, Me.metadataArray.Length)
        XMLArray = Split(MyUtil.arrayToString(Me.metadataArray, "|"), "|")

        count = UBound(XMLArray) - 1

        ' Encode strings so there won't be XML parsing error.
        For i = 0 To count
            XMLArray(i) = XMLEncode(XMLArray(i))
        Next

        Dim str As String
        str = str & "<?xml version=" & Chr(34) & "1.0" & Chr(34) & " ?>" & vbCrLf
        str = str & "<!--This XML file is created by XinCoder 1.0-->" & vbCrLf
        str = str & "<!--Author: Xin Chen                        -->" & vbCrLf
        str = str & "<!--Release time: November 8th, 2003        -->" & vbCrLf
        str = str & "<!--Email: chenx@hawaii.edu                 -->" & vbCrLf
        str = str & vbCrLf & vbCrLf

        str = str & "<XinCoderMetadata>" & vbCrLf
        str = str & vbCrLf & vbCrLf
        str = str & "<createDate>" & Today() & "</createDate>" & vbCrLf
        str = str & vbCrLf & vbCrLf

        For i = 0 To count
            If LCase(XMLArray(i + 1)) = "text" Or LCase(XMLArray(i + 1)) = "password" Or LCase(XMLArray(i + 1)) = "hidden" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<label>" & XMLArray(i) & "</label>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<htmlName>" & XMLArray(i + 2) & "</htmlName>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<size>" & XMLArray(i + 3) & "</size>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<maxlength>" & XMLArray(i + 4) & "</maxlength>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<databaseName>" & XMLArray(i + 5) & "</databaseName>" & vbCrLf
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 5
            ElseIf LCase(XMLArray(i + 1)) = "select" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<label>" & XMLArray(i) & "</label>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<htmlName>" & XMLArray(i + 2) & "</htmlName>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<width>" & XMLArray(i + 3) & "</width>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<size>" & XMLArray(i + 4) & "</size>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<optionCount>" & XMLArray(i + 5) & "</optionCount>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<databaseName>" & XMLArray(i + 6) & "</databaseName>" & vbCrLf
                count = CInt(XMLArray(i + 5))
                For j = 1 To count
                    str = str & XMLIndent & XMLIndent & "<option>" & XMLArray(i + 6 + j) & "</option>" & vbCrLf
                Next
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 5 + count
            ElseIf LCase(XMLArray(i + 1)) = "textarea" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<label>" & XMLArray(i) & "</label>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<htmlName>" & XMLArray(i + 2) & "</htmlName>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<rows>" & XMLArray(i + 3) & "</rows>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<cols>" & XMLArray(i + 4) & "</cols>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<wrap>" & XMLArray(i + 5) & "</wrap>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<databaseName>" & XMLArray(i + 6) & "</databaseName>" & vbCrLf
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 6
            ElseIf LCase(XMLArray(i + 1)) = "radio" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<label>" & XMLArray(i) & "</label>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<htmlName>" & XMLArray(i + 2) & "</htmlName>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<choiceCount>" & XMLArray(i + 3) & "</choiceCount>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<databaseName>" & XMLArray(i + 4) & "</databaseName>" & vbCrLf
                count = CInt(XMLArray(i + 3))
                For j = 1 To count
                    str = str & XMLIndent & XMLIndent & "<choice>" & XMLArray(i + 4 + j) & "</choice>" & vbCrLf
                Next
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 3 + count
            ElseIf LCase(XMLArray(i + 1)) = "checkbox" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<label>" & XMLArray(i) & "</label>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<htmlName>" & XMLArray(i + 2) & "</htmlName>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<value>" & XMLArray(i + 3) & "</value>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<databaseName>" & XMLArray(i + 4) & "</databaseName>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<text>" & XMLArray(i + 5) & "</text>" & vbCrLf
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 4
            ElseIf LCase(XMLArray(i + 1)) = "comment" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<label>" & XMLArray(i) & "</label>" & vbCrLf
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 1
            ElseIf LCase(XMLArray(i + 1)) = "blankline" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<numOfLines>" & XMLArray(i) & "</numOfLines>" & vbCrLf
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 1
            ElseIf LCase(XMLArray(i + 1)) = "hr" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<placeHolder>" & XMLArray(i) & "</placeHolder>" & vbCrLf
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 1
            ElseIf LCase(XMLArray(i + 1)) = "newtable" Then
                str = str & XMLIndent & "<field>" & vbCrLf
                fieldsCounter = fieldsCounter + 1
                str = str & XMLIndent & XMLIndent & "<fieldsCounter>" & fieldsCounter & "</fieldsCounter>" & vbCrLf

                str = str & XMLIndent & XMLIndent & "<type>" & XMLArray(i + 1) & "</type>" & vbCrLf
                str = str & XMLIndent & XMLIndent & "<tableFirstColWidth>" & XMLArray(i) & "</tableFirstColWidth>" & vbCrLf
                str = str & XMLIndent & "</field>" & vbCrLf
                i = i + 1
            End If
        Next

        str = str & vbCrLf
        str = str & "</XinCoderMetadata>" & vbCrLf

        Return str
    End Function


    Public Function getMetadataExample()
        Dim str As String = ""

        str = str & vbCrLf
        str = str & "Login name:|text|txtAccount|20|50|account|" & vbCrLf
        str = str & "Password:|password|txtPassword|20|50|password|" & vbCrLf
        str = str & "Repeat Password:|password|txtPassword2|20|50|password2|" & vbCrLf
        str = str & vbCrLf
        str = str & "First Name:|text|txtFirstName|20|50|firstName|" & vbCrLf
        str = str & "Last Name:|text|txtLastName|20|50|lastName|" & vbCrLf
        str = str & vbCrLf
        str = str & "E-mail:|text|txtEmail|20|50|email|" & vbCrLf
        str = str & "This is test for comment|comment|" & vbCrLf
        str = str & "hr|hr|" & vbCrLf
        str = str & "campus info|select|cmbCampus|300|1|15|campus|No|UH Manoa|UH Hilo|UH West Oahu|Hawaii Community College|Honolulu Community College|Kapiolani Community College|Kauai Community College|Leeward Community College|Maui Community College|Windward Community College|LCC Waianae Education Center|MCC Molokai Education Center|MCC Lanai Education Center|MCC Hana Education Center|" & vbCrLf
        str = str & "Project involvement|textarea|taProjInvolvement|10|35|WRAP|projInvolvement|" & vbCrLf
        str = str & "sex: |radio|rbSex|2|sex|Male|Female|" & vbCrLf
        str = str & "Ethnicity|checkbox|cbEth1|Y|eth1|African American|" & vbCrLf
        str = str & "20|newtable|" & vbCrLf

        Return str
    End Function



    ''''''''''''''''''''''''''''''''''''''''''''
    ' Regitration include/regFuncs.asp
    ''''''''''''''''''''''''''''''''''''''''''''

    Public Function writeFunctionComment(ByVal comment As String)
        Dim str As String = ""
        str = str & vbCrLf & vbCrLf
        str = str & "'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''" & vbCrLf
        str = str & "' " & comment & vbCrLf
        str = str & "'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''" & vbCrLf
        str = str & vbCrLf
    End Function



    Public Function previewEditTable()
        Dim i, j, count As Integer
        Dim tdWidth As String
        Dim str As String = ""

        Dim tableStart As String = "<table "
        If tableBorder <> "" Then tableStart &= " border=" & tableBorder
        If tableWidth <> "" Then tableStart &= " width=" & tableWidth
        If tablebgcolor <> "" Then tableStart &= " bgcolor=" & tablebgcolor
        If tableCellpadding <> "" Then tableStart &= " cellpadding=" & tableCellpadding
        If tableCellspacing <> "" Then tableStart &= " cellspacing=" & tableCellspacing
        tableStart &= ">"

        str = str & tableStart & vbCrLf

        count = UBound(metadataArray) - 1
        For i = 0 To count
            If LCase(metadataArray(i + 1)) = "text" Or LCase(metadataArray(i + 1)) = "password" Or LCase(metadataArray(i + 1)) = "hidden" Then
                If tableFirstColWidth <> "" Then
                    str = str & ("<tr><td valign=top width=" & tableFirstColWidth & ">") & vbCrLf
                Else
                    str = str & ("<tr><td valign=top>") & vbCrLf
                End If
                str = str & (metadataArray(i)) & vbCrLf ' label
                str = str & ("</td><td valign=top>") & vbCrLf
                str = str & ("<input type=" & metadataArray(i + 1) & " name=" & metadataArray(i + 2) & " size=" & metadataArray(i + 3) & " maxlength=" & metadataArray(i + 4) & " value=" & Chr(34) & Chr(34) & ">") & vbCrLf
                str = str & ("</td></tr>") & vbCrLf
                i = i + 5
            ElseIf LCase(metadataArray(i + 1)) = "select" Then
                str = str & ("<tr><td valign=top>") & vbCrLf
                str = str & (metadataArray(i)) & vbCrLf
                str = str & ("</td><td valign=top>") & vbCrLf
                str = str & ("<select name=" & metadataArray(i + 2) & " style=" & Chr(34) & "WIDTH: " & metadataArray(i + 3) & Chr(34) & " size=" & metadataArray(i + 4) & ">") & vbCrLf
                count = CInt(metadataArray(i + 5))
                For j = 1 To count
                    str = str & ("<option value=" & j & ">" & metadataArray(i + 6 + j)) & vbCrLf
                Next
                str = str & ("</select>") & vbCrLf
                str = str & ("</td></tr>") & vbCrLf
                i = i + 5 + count
            ElseIf LCase(metadataArray(i + 1)) = "textarea" Then
                str = str & ("<tr><td valign=top>") & vbCrLf
                str = str & (metadataArray(i)) & vbCrLf
                str = str & ("</td><td valign=top>") & vbCrLf
                str = str & ("<TEXTAREA NAME=" & metadataArray(i + 2) & " ROWS=" & CInt(metadataArray(i + 3)) & " COLS=" & CInt(metadataArray(i + 4)) & " " & metadataArray(i + 5) & "></TEXTAREA>") & vbCrLf
                str = str & ("</td></tr>") & vbCrLf
                i = i + 6
            ElseIf LCase(metadataArray(i + 1)) = "radio" Then
                str = str & ("<tr><td valign=top>") & vbCrLf
                str = str & (metadataArray(i)) & vbCrLf
                str = str & ("</td><td valign=top>") & vbCrLf
                count = CInt(metadataArray(i + 3))
                For j = 1 To count
                    str = str & (metadataArray(i + 4 + j) & "<input type=radio name=" & metadataArray(i + 2) & " value=" & j & ">") & vbCrLf
                Next
                str = str & ("</td></tr>") & vbCrLf
                i = i + 3 + count
            ElseIf LCase(metadataArray(i + 1)) = "checkbox" Then
                str = str & ("<tr><td valign=top>") & vbCrLf
                str = str & (metadataArray(i)) & vbCrLf
                str = str & ("</td><td valign=top>") & vbCrLf
                'str = str &  "<input type=checkbox name=" & chr(34) & metadataArray(i+2) & chr(34) & " value=" & chr(34) & metadataArray(i+3) & chr(34) & " <" & "%if session(" & chr(34) & metadataArray(i+4) & chr(34) & ") <> " & chr(34) & chr(34) & " then%" & "> checked <" & "%end if%" & ">>" & metadataArray(i+5)
                ' Note: Now the value is hardcoded to "Y".
                str = str & ("<input type=checkbox name=" & Chr(34) & metadataArray(i + 2) & Chr(34) & " value=" & Chr(34) & "Y" & Chr(34) & ">" & metadataArray(i + 5)) & vbCrLf
                str = str & ("</td></tr>") & vbCrLf
                i = i + 4
            ElseIf LCase(metadataArray(i + 1)) = "comment" Then
                str = str & ("<tr><td valign=top colspan=2>") & vbCrLf
                str = str & (metadataArray(i)) & vbCrLf
                str = str & ("</td></tr>") & vbCrLf
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "blankline" Then
                str = str & ("<tr><td valign=top colspan=2>") & vbCrLf
                For j = 1 To CInt(metadataArray(i))
                    str = str & ("<br>") & vbCrLf
                Next
                str = str & ("</td></tr>") & vbCrLf
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "hr" Then
                str = str & ("<tr><td valign=top colspan=2>") & vbCrLf
                str = str & ("<hr>") & vbCrLf
                str = str & ("</td></tr>") & vbCrLf
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "newtable" Then
                str = str & ("</table>") & vbCrLf
                str = str & tableStart & vbCrLf
                tdWidth = metadataArray(i)
                If tdWidth <> "" Then
                    str = str & "<tr><td width=" & tdWidth & "><br></td>" & "<td><br></td></tr>" & vbCrLf
                ElseIf Me.tableFirstColWidth <> "" Then
                    str = str & "<tr><td width=" & Me.tableFirstColWidth & "><br></td>" & "<td><br></td></tr>" & vbCrLf
                Else
                    str = str & "<tr><td><br></td>" & "<td><br></td></tr>" & vbCrLf
                End If

                'tdWidth = CInt(metadataArray(i))
                'If tdWidth >= 0 And tdWidth <= 100 Then
                'str = str & "<tr><td width=" & tdWidth & "%" & "><br></td>" & "<td width=" & (100 - tdWidth) & "%" & "><br></td></tr>" & vbCrLf
                'End If
                i = i + 1
            End If

        Next

        str = str & ("</table>") & vbCrLf
        Return str
    End Function



    Public Function previewEditTable_Custom()
        Dim i, j, count, tdWidth As Integer
        Dim str As String = ""

        count = UBound(metadataArray) - 1
        For i = 0 To count
            If LCase(metadataArray(i + 1)) = "text" Or LCase(metadataArray(i + 1)) = "password" Or LCase(metadataArray(i + 1)) = "hidden" Then
                str = str & (metadataArray(i)) & vbCrLf ' label
                str = str & ("<input type=" & metadataArray(i + 1) & " name=" & metadataArray(i + 2) & " size=" & metadataArray(i + 3) & " maxlength=" & metadataArray(i + 4) & " value=" & Chr(34) & Chr(34) & ">") & vbCrLf
                i = i + 5
            ElseIf LCase(metadataArray(i + 1)) = "select" Then
                str = str & (metadataArray(i)) & vbCrLf
                str = str & ("<select name=" & metadataArray(i + 2) & " style=" & Chr(34) & "WIDTH: " & metadataArray(i + 3) & Chr(34) & " size=" & metadataArray(i + 4) & ">") & vbCrLf
                count = CInt(metadataArray(i + 5))
                For j = 1 To count
                    str = str & ("<option value=" & j & ">" & metadataArray(i + 6 + j)) & vbCrLf
                Next
                str = str & ("</select>") & vbCrLf
                i = i + 5 + count
            ElseIf LCase(metadataArray(i + 1)) = "textarea" Then
                str = str & (metadataArray(i)) & vbCrLf
                str = str & ("<TEXTAREA NAME=" & metadataArray(i + 2) & " ROWS=" & CInt(metadataArray(i + 3)) & " COLS=" & CInt(metadataArray(i + 4)) & " " & metadataArray(i + 5) & "></TEXTAREA>") & vbCrLf
                i = i + 6
            ElseIf LCase(metadataArray(i + 1)) = "radio" Then
                str = str & (metadataArray(i)) & vbCrLf
                count = CInt(metadataArray(i + 3))
                For j = 1 To count
                    str = str & (metadataArray(i + 4 + j) & "<input type=radio name=" & metadataArray(i + 2) & " value=" & j & ">") & vbCrLf
                Next
                i = i + 3 + count
            ElseIf LCase(metadataArray(i + 1)) = "checkbox" Then
                str = str & (metadataArray(i)) & vbCrLf
                'str = str &  "<input type=checkbox name=" & chr(34) & metadataArray(i+2) & chr(34) & " value=" & chr(34) & metadataArray(i+3) & chr(34) & " <" & "%if session(" & chr(34) & metadataArray(i+4) & chr(34) & ") <> " & chr(34) & chr(34) & " then%" & "> checked <" & "%end if%" & ">>" & metadataArray(i+5)
                ' Note: Now the value is hardcoded to "Y".
                str = str & ("<input type=checkbox name=" & Chr(34) & metadataArray(i + 2) & Chr(34) & " value=" & Chr(34) & "Y" & Chr(34) & ">" & metadataArray(i + 5)) & vbCrLf
                i = i + 4
            ElseIf LCase(metadataArray(i + 1)) = "comment" Then
                str = str & (metadataArray(i)) & vbCrLf
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "blankline" Then
                For j = 1 To CInt(metadataArray(i))
                    str = str & ("<br>") & vbCrLf
                Next
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "hr" Then
                str = str & ("<hr>") & vbCrLf
                i = i + 1
            ElseIf LCase(metadataArray(i + 1)) = "newtable" Then
                i = i + 1
            End If

        Next

        Return str
    End Function

End Class
